name: Release Snapshot

on:
  release:
    types: [published]
  pull_request:

jobs:
  release_npm:
    name: Release to npm
    runs-on: ubuntu-latest
    # if: "github.event.release.prerelease"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: sbt

      # - name: Create .npmrc
      #   env:
      #     NPM_TOKEN: ${{ secrets.GB_NPM_TOKEN }}
      #   run: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > $HOME/.npmrc'
      
      - name: Release Snapshot to NPM
        run: scripts/ci/release-snapshot-npm.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}