name: Release

on:
  push
  
jobs:
  release-npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: sbt
        
      - name: Get build version
        id: project
        run: echo ::set-output name=version::$(scripts/getVersion.sh)

      - name: Release to NPM
        run: sbt "project tsApiModels" "releaseNpm ${{ steps.project.outputs.version }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}