# This action runs on every push to `main`
# If the branch it's running on is main then it will run snyk monitor (reports vulnerabilities to snyk.io)

name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      SKIP_NODE: true
      ORG: guardian-dotcom-n2y
      JAVA_VERSION: 11
      PROJECT_FILE: ./build.sbt
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
