name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: guardian/setup-scala@v1

      - name: Test model
        run: sbt "clean" "project scalaApiModels" "set isSnapshot := false" "compile"
